# mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppet-nginx', '1.1.0'
mod 'puppetlabs-postgresql', '6.3.0'
mod 'puppetlabs-mysql', '10.4.0'
mod 'darkmantle-lamp', '1.1.0'
mod 'swizzley88-wordpress', '0.1.2'
#mod 'puppetlabs-apache', '5.4.0'
mod 'example42-apache', '2.1.13'
